repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.0.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]